name: Autofix (format & lint)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1-5"  # καθημερινές 05:00 Ελλάδας

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install tools
        run: pip install ruff black isort

      - name: Run formatters
        run: |
          ruff check . --fix || true
          isort . || true
          black . || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(autofix): apply ruff/black/isort fixes [skip ci]"
          title: "chore(autofix): code style fixes"
          body: "Automated formatting & lint fixes."
          branch: ci/autofix
          delete-branch: true
          labels: "autofix"
