name: Auto Format Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    name: Auto-fix lint violations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatters
        run: |
          pip install black ruff

      - name: Run auto-fixes
        run: |
          black . --quiet
          ruff check . --fix

      - name: Commit & Push changes
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && env.ACT != 'true' }}
        run: |
          git config user.name "🤖 Auto Formatter"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "style: auto-fix lint/format issues"
          git push origin HEAD
