name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      run_integration:
        description: "Run integration tests"
        type: boolean
        default: false

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint_and_unit:
    name: Lint & Unit (fast)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install deps (cached)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install pytest-xdist

      - name: Determine changed Python files
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base="${{ github.event.pull_request.base.sha }}"
            head="${{ github.event.pull_request.head.sha }}"
          else
            # fallback: compare to merge-base with origin/main if available
            git fetch --no-tags --depth=1 origin main || true
            base="$(git merge-base HEAD origin/main || echo HEAD^)"
            head="${GITHUB_SHA}"
          fi
          files=$(git diff --name-only "$base" "$head" | grep -E '\.py$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Ruff (changed files only)
        if: ${{ steps.diff.outputs.files != '' }}
        run: |
          echo "${{ steps.diff.outputs.files }}" | tr '\n' ' ' | xargs -r ruff check --select I,E,F,UP
      - name: Ruff (fallback whole repo)
        if: ${{ steps.diff.outputs.files == '' }}
        run: ruff check --select I,E,F,UP .

      - name: Black check (changed files only)
        if: ${{ steps.diff.outputs.files != '' }}
        run: |
          echo "${{ steps.diff.outputs.files }}" | tr '\n' ' ' | xargs -r black --check
      - name: Black check (fallback whole repo)
        if: ${{ steps.diff.outputs.files == '' }}
        run: black --check .

      - name: Run unit tests (parallel) with coverage
        run: |
          pytest -q -m "not integration" -n auto \
            --cov=hcebt --cov=lib --cov-report=xml

      - name: Upload coverage to Codecov (main only)
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration:
    name: Integration (on demand)
    runs-on: ubuntu-latest
    timeout-minutes: 35
    needs: [lint_and_unit]
    if: |
      github.event_name == 'workflow_dispatch' && inputs.run_integration == true
      || (github.event_name == 'push' && contains(github.event.head_commit.message, '[it]'))
      || (github.event_name == 'pull_request' && contains(github.head_ref, 'it/'))

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.8
        ports: ['8123:8123']
        options: >-
          --health-cmd="wget -qO- http://localhost:8123/ping || exit 1"
          --health-interval=5s --health-timeout=2s --health-retries=30
      timescale:
        image: timescale/timescaledb:2.16.1-pg15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hce
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres -d hce"
          --health-interval=5s --health-timeout=2s --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install deps (cached)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run integration tests
        env:
          IT_CLICKHOUSE: "1"
          IT_TIMESCALE: "1"
          CLICKHOUSE_URL: "http://localhost:8123"
          TIMESCALE_DSN: "postgresql://postgres:postgres@localhost:5432/hce"
        run: |
          pytest -q -m "integration"
