name: HCE Python CI (lint, unit, integration)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (incl. pytest-cov, ruff, black)
        shell: bash
        run: |
          python -m pip install -U pip wheel
          # project deps
          if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
          if [[ -f requirements-dev.txt ]]; then pip install -r requirements-dev.txt; fi
          # tooling
          pip install pytest pytest-cov ruff black

      # Κύρια βήματα: αν αποτύχουν -> job failure
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Tests + Coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=. --cov-report=xml --cov-report=term

      # Συλλογή logs/coverage ΠΑΝΤΑ, για σχόλιο στο PR
      - name: Collect key logs (always)
        if: ${{ always() }}
        shell: bash
        run: |
          mkdir -p ci_logs
          echo "==== ruff ===="    >  ci_logs/ruff.txt;   (ruff check . || true)    2>&1 | tee -a ci_logs/ruff.txt
          echo "==== black ===="   >  ci_logs/black.txt;  (black --check . || true) 2>&1 | tee -a ci_logs/black.txt
          echo "==== pytest ===="  >  ci_logs/pytest.txt; (pytest -q || true)       2>&1 | tee -a ci_logs/pytest.txt
          # coverage artifacts αν υπάρχουν
          [[ -f coverage.xml ]] && cp coverage.xml ci_logs/ || true
          [[ -f .coverage ]] && cp .coverage ci_logs/ || true

      - name: Upload artifacts (logs + coverage)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            ci_logs/
            reports/
            logs/
          if-no-files-found: ignore

  post_fail_comment:
    needs: [test]
    if: ${{ failure() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download logs artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ci_logs

      - name: Comment failure summary to PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            function tail4k(p) {
              try { return fs.readFileSync(p, 'utf8').slice(-4000); }
              catch { return '(not found)'; }
            }

            const ruff = tail4k('ci_logs/ruff.txt');
            const black = tail4k('ci_logs/black.txt');
            const pytest = tail4k('ci_logs/pytest.txt');

            const body = [
              '### ❌ CI failed — key excerpts',
              '```txt\n[ruff]\n' + ruff + '\n```',
              '```txt\n[black]\n' + black + '\n```',
              '```txt\n[pytest]\n' + pytest + '\n```',
              `Run logs: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            ].join('\n\n');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
