feature:
  - changed-files:
      any-glob-to-any-file:
        - "**/*.py"
        - "src/**"
        - "packages/**"

bug:
  - changed-files:
      any-glob-to-any-file:
        - "**/*fix*"
        - "hotfix/**"

docs:
  - changed-files:
      any-glob-to-any-file:
        - "docs/**"
        - "**/*.md"

chore:
  - changed-files:
      any-glob-to-any-file:
        - ".github/**"

tests:
  - changed-files:
      any-glob-to-any-file:
        - "tests/**"
        - "**/test_*.py"
        - "**/*_test.py"
        - "**/*.spec.ts"
        - "**/*.test.ts"
        - "**/*.spec.tsx"
        - "**/*.test.tsx"

ci:
  - changed-files:
      any-glob-to-any-file:
        - ".github/workflows/**"
        - ".github/labeler.yml"
