name: PR Lint Suggestions

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  pull-requests: write

jobs:
  ruff_review:
    name: Ruff Suggestion Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ruff & reviewdog
        run: |
          pip install ruff
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
        env:
          REVIEWDOG_VERSION: latest

      - name: Run ruff and report with reviewdog
        run: |
          ruff check --format=github . | ./bin/reviewdog -f=github -reporter=github-pr-review -filter-mode=diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black_review:
    name: Black Suggestion Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black & reviewdog
        run: |
          pip install black
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
        env:
          REVIEWDOG_VERSION: latest

      - name: Run black and report with reviewdog
        run: |
          black --check --diff . | ./bin/reviewdog -efm="%f:%l:%c: %m" -name="black" -reporter=github-pr-review -filter-mode=diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
