name: Nightly Full

on:
  schedule:
    - cron: "30 23 * * *"  # 02:30 Athens
  workflow_dispatch:

jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt
          ruff check .
          black --check .
          pytest -q

