name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # Note: We use pull_request_target without checking out PR code for security.
      # This prevents malicious PRs from accessing secrets or modifying the repository.
      # The labeler action reads the configuration from the base branch by default.
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
          dot: true
