name: PR Lite (ruff)

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: |
          python -m pip install -U pip
          pip install ruff==0.5.7
          ruff check --output-format=github .

