name: Release Please

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: hce
          bump-minor-pre-major: true
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"perf","section":"Performance","hidden":false},
             {"type":"docs","section":"Docs","hidden":false},
             {"type":"refactor","section":"Refactors","hidden":false},
             {"type":"chore","section":"Chores","hidden":false},
             {"type":"test","section":"Tests","hidden":false}]

