name: Scheduled Backtest/Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # 00:00 Europe/Athens

permissions:
  contents: read

jobs:
  backtest:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run backtest (if script exists)
        shell: bash
        env:
          EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
          EXCHANGE_API_SECRET: ${{ secrets.EXCHANGE_API_SECRET }}
        run: |
          if [ -f scripts/backtest.py ]; then
            python scripts/backtest.py --quick || true
          elif [ -f scripts/smoke.py ]; then
            python scripts/smoke.py || true
          else
            echo "No backtest/smoke script, skipping"
          fi

