name: Run Unit Tests (disabled)

on:
  workflow_dispatch:

jobs:
  test:
    if: ${{ false }} # disabled in favor of Push Full workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package + dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          pytest -q -m "not integration" -n auto --cov=hcebt --cov-report=xml
